//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDataStockAnalysis.Properties
{
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Java")]
        public string JAVA_WIN_PATH {
            get {
                return ((string)(this["JAVA_WIN_PATH"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("output")]
        public string WIN_OUTPUT_PATH {
            get {
                return ((string)(this["WIN_OUTPUT_PATH"]));
            }
            set {
                this["WIN_OUTPUT_PATH"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CanopyKMeansJob")]
        public string JAVA_MAIN_CLASS_NAME {
            get {
                return ((string)(this["JAVA_MAIN_CLASS_NAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("input")]
        public string INPUT_WIN_PATH {
            get {
                return ((string)(this["INPUT_WIN_PATH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CanopyKMeans")]
        public string CLOUDERA_PATH {
            get {
                return ((string)(this["CLOUDERA_PATH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("input")]
        public string INPUT_CLOUDERA_FOLDER {
            get {
                return ((string)(this["INPUT_CLOUDERA_FOLDER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Java")]
        public string JAVA_CLOUDERA_FOLDER {
            get {
                return ((string)(this["JAVA_CLOUDERA_FOLDER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("output")]
        public string CLOUDERA_OUTPUT_FOLDER {
            get {
                return ((string)(this["CLOUDERA_OUTPUT_FOLDER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("classes")]
        public string CLASSES_FOLDER {
            get {
                return ((string)(this["CLASSES_FOLDER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CanopyKMeans.jar")]
        public string JAR_NAME {
            get {
                return ((string)(this["JAR_NAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CanopyKMeans")]
        public string MAP_REDUCE_FOLDER {
            get {
                return ((string)(this["MAP_REDUCE_FOLDER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/usr/lib/hadoop/*:/usr/lib/hadoop/client-0.20/*")]
        public string CLOUDERA_COMPILED_CLASS_PATH {
            get {
                return ((string)(this["CLOUDERA_COMPILED_CLASS_PATH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("training")]
        public string USER_NAME_FOR_HOST {
            get {
                return ((string)(this["USER_NAME_FOR_HOST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("training")]
        public string PASSWORD_FOR_HOST {
            get {
                return ((string)(this["PASSWORD_FOR_HOST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CanopyKMeans")]
        public string PACKAGE_NAME {
            get {
                return ((string)(this["PACKAGE_NAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string MAX_ROW_NUMBER_INPUT_FILE {
            get {
                return ((string)(this["MAX_ROW_NUMBER_INPUT_FILE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.0.0.9")]
        public string IP_ADDRESS {
            get {
                return ((string)(this["IP_ADDRESS"]));
            }
        }
    }
}
